---
title: 'Data 624: Project 1'
author: "Group 2: Alice Friedman, Kayleah Griffen, Josh Iden, Michael Ippolito"
date: "6/11/2023"
output:
  word_document: 
    toc: true
always_allow_html: true
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.path='Figs/', echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE)
```

## Data Preparation
```{r setup, warning=FALSE, echo = FALSE}
library(httr)
library(kableExtra)
library(fpp2)
library(imputeTS)
library(tidyverse)
library(urca)
library(ggfortify)
library(gridExtra)
library(scales)
library(flextable)
library(openxlsx)
set.seed(123)

# Set minimal theme
theme_set(theme_minimal())

```

```{r get_data, warning=FALSE, echo = FALSE}
github_link <- "https://github.com/klgriffen96/summer23_data624/raw/main/project_1/Data%20Set%20for%20Class.xls"
temp_file <- tempfile(fileext = ".xls")
req <- GET(github_link, 
          # write result to disk
           write_disk(path = temp_file))

df <- readxl::read_excel(temp_file)

head(df, 10) |>
  flextable()
```

```{r slice}
#Split the data into data frames by category and var name

df_long <- df %>% gather(key, value, -SeriesInd, -category)
split_data <- split(df_long, f=list(df_long$category, df_long$key))


#put the combo into a list so it can be run through
list_vars <- c(
  "S01.Var01", "S01.Var02",
  "S02.Var02", "S02.Var03",
  "S03.Var05", "S03.Var07",
  "S04.Var01", "S04.Var02",
  "S05.Var02", "S05.Var03",
  "S06.Var05", "S06.Var07"
)

#select list items based on the list vars and then turn each list item 
myts_raw <- lapply(split_data[list_vars], function(x) {
    x %>% 
    dplyr::select(value) %>% 
    slice(1:1622) %>% #removes the missing values we need to predict
    ts()
})


#select list items based on the list vars and then turn each list item into a clean ts
myts <- lapply(split_data[list_vars], function(x) {
    x %>% 
    dplyr::select(value) %>% 
    slice(1:1622) %>% #removes the missing values we need to predict
    ts() %>% 
    tsclean() %>%
    na_ma() 
})

```


```{r data-exploration}

plot_grid <- function(df){
# Takes as input a dataframe which is a list of ts objects  

# Create an empty list to store the plots
plot_list <- list()

# Generate the plots and store them in the plot_list
for (var in list_vars) {
  ts <- df[[var]]
  plot <- autoplot(ts) + ggtitle(var) + scale_y_continuous(labels = scales::comma)  # Customize y-axis labels
  plot_list[[var]] <- plot
}

# Arrange the plots in a grid
grid_arranged_plots <- do.call(grid.arrange, c(plot_list, ncol = 4))

# Print the grid of plots
print(grid_arranged_plots)
}

plot_grid(myts_raw)
plot_grid(myts)
```

Using the function `ndiffs` we can see that each series requires 1 differencing to become stationary.

```{r backtransform-diff}
# Function to backtransorm differencing
back_diff <- function(diff_t, t1){
  
  # Append the initial value
  init <- append(t1, diff_t)
  
  # Cumsum the diffed series with the inital value as the first item
  backtransformed_series <- cumsum(init)
  
  # Return result  
  return(backtransformed_series)
  
  }
  
```

```{r ses_define_func}

# Create a function to test the ses and holt forecasts with test and train data
ses_test <- function(x, i, log=FALSE) {
  
  # Determine the index to split the time series into train and test sets
  split.index <- floor(0.8 * length(x))  # 80% for training, 20% for testing
  
  # Split the time series into train and test sets
  train <- window(x, end = split.index) 
  test <- window(x, start = split.index + 1)
  
  # Set the horizon
  horizon <- length(test)
  
  ######## FOR LOG TRANSFORMED
  if(log==TRUE){
    train <- log(train)
    # Ses fit with training data
    ses.fit <- ses(train, h = horizon)$mean %>% 
      exp() %>% 
      ts(start=split.index + 1)

    # Test with test data BACKTRANSFORMED
    ses_res <- accuracy(ses.fit, test)['Test set', 'MAPE']
  
    # Holt fit with training data
    holt.fit <- holt(train, damped = TRUE, h = horizon)$mean %>% 
      exp() %>% 
      ts(start=split.index + 1)

    # Test with test data
    holt_res <- accuracy(holt.fit, test)['Test set', 'MAPE']
  }
  
  
  ####### NO TRANSFORM
  else{
    # Ses fit with training data
    ses.fit <- ses(train, h = horizon)

    # Test with test data
    ses_res <- accuracy(ses.fit, test)['Test set', 'MAPE']
  
    # Holt fit with training data
    holt.fit <- holt(train, damped = TRUE, h = horizon)

    # Test with test data
    holt_res <- accuracy(holt.fit, test)['Test set', 'MAPE']
  }

  ######################
  # Create a plot
  p <- autoplot(window(x, end=split.index)) +
    autolayer(ses.fit, series = "ses") + #ses forecast
    autolayer(holt.fit, alpha = 0.4, series = "holt") +
    autolayer(test, series = "Test data") +
    ggtitle(paste(list_vars[i], "Exponential Smoothing Forecasts"))
  
  # Return list of results
  result <- list(ses_MAPE = ses_res, #1
                 holt_MAPE = holt_res #2
                )
  
  print(p)
  return(result)
}
```




```{r run_ses}
# Create the empty vectors
smooth_results <- vector(mode = "list", length = length(myts))
ses_MAPE <- vector("numeric", length = length(list_vars))
holt_MAPE <- vector("numeric", length = length(list_vars))
ses_p <- vector("numeric", length = length(list_vars))
holt_p <- vector("numeric", length = length(list_vars))

# Run through the function to build the lists
for (i in seq_along(myts)) {
  result <- ses_test(myts[[i]], i, F)
  ses_MAPE[i] <- result[1]
  holt_MAPE[i] <- result[2]
}
```

```{r arima}
# Create the empty vectors
arima_MAPE_lambda0 <- vector(mode = "list", length = length(myts))
arima_MAPE_lambda1 <- vector(mode = "list", length = length(myts))

# Create a function to test the ses and holt forecasts with test and train data
arima_test <- function(x, i, lambda) {
  
  # Determine the index to split the time series into train and test sets
  split.index <- floor(0.8 * length(x))  # 80% for training, 20% for testing
  
  # Split the time series into train and test sets
  train <- window(x, end = split.index)
  test <- window(x, start = split.index + 1)
  
  # Set the horizon
  horizon <- length(test)
  
  #auto arima fit
  arima.fc <-  train %>% 
  auto.arima(lambda = lambda) %>%
  forecast(h=horizon)
  
  # test results
  result <- accuracy(arima.fc, test)['Test set', 'MAPE']
  
  #plot residuals
  #p <- checkresiduals(arima.fc)
  p <- autoplot(arima.fc) +
    autolayer(test) +
    ggtitle(list_vars[i])

  print(p)
  
  return(result)
}


## Run 
for (i in seq_along(myts)) {
  arima_MAPE_lambda0[i]<- do.call(arima_test, list(myts[[i]], i, 0))
  arima_MAPE_lambda1[i]<- do.call(arima_test, list(myts[[i]], i, 1))
}
```

```{r results_mape}
results_df<- cbind(
  list_vars,
  ses_MAPE,
  holt_MAPE,
  arima_MAPE_lambda0,
  arima_MAPE_lambda1
)
# Print the results as a table
results_df # %>% flextable()
```
## Forecast

```{r forecasts}
SeriesInd <- df_long$SeriesInd %>% unique()

forecasts <- lapply(myts, function(x){

  ses.fit <- ses(x, h = 140)
  
  cbind(SeriesInd, 
        append(x, ses.fit$mean))
})



```

```{r export}
S01 <- merge(forecasts$S01.Var01, forecasts$S01.Var02, by = "SeriesInd")
names(S01) <- c("SeriesInd", "Var01", "Var02")

S02 <- merge(forecasts$S02.Var02, forecasts$S02.Var03, by = "SeriesInd")
names(S02) <- c("SeriesInd", "Var02", "Var03")

S03 <- merge(forecasts$S03.Var05, forecasts$S03.Var07, by = "SeriesInd")
names(S03) <- c("SeriesInd", "Var05", "Var07")

S04 <- merge(forecasts$S04.Var01, forecasts$S04.Var02, by = "SeriesInd")
names(S04) <- c("SeriesInd", "Var01", "Var02")

S05 <- merge(forecasts$S05.Var02, forecasts$S05.Var03, by = "SeriesInd")
names(S05) <- c("SeriesInd", "Var02", "Var03")

S06 <- merge(forecasts$S06.Var05, forecasts$S06.Var07, by = "SeriesInd")
names(S06) <- c("SeriesInd", "Var05", "Var07")

export <- list(
  S01=S01,
  S02=S02,
  S03=S03,
  S04=S04,
  S05=S05,
  S06=S06
)
#reference: https://www.statology.org/r-export-to-excel-multiple-sheets/
#export each data frame to separate sheets in same Excel file
openxlsx::write.xlsx(export, file = 'group2_forecasts.xlsx') 
```

## Appendix 1: R Code
```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE} 

```